/* generated by scripts/sync-inference-catalog.mjs */
export const INFERENCE_CATALOG_SOURCE_STATUS = {
  models: {
    url: 'https://models.dev/models.json',
    fetchedAt: '2026-09-26T14:12:16.117Z',
    checkedAt: '2026-09-27T00:45:28.081Z',
    sha256: '1628b99884d9d2ae5446be7d9c5cd0ab97360b12637ad10f21c28fc062b87e1c',
  },
  providers: {
    url: 'https://models.dev/api.json',
    fetchedAt: '2026-09-27T00:45:28.140Z',
    checkedAt: '2026-09-27T00:45:28.140Z',
    sha256: 'da2577060e561ae821c5c589697751cc3b0751a4c9fb6f1c3b148fb5fc728f9e',
  },
  venice: {
    url: 'https://api.venice.ai/api/v1/models',
    fetchedAt: '2026-09-27T00:45:28.192Z',
    checkedAt: '2026-09-27T00:45:28.192Z',
    sha256: '5400b67f1b3711db56978e0485bacc60936f7736a0f2f3c97a09d874fb726e47',
  },
  redpill: {
    url: 'https://api.redpill.ai/v1/models',
    fetchedAt: '2026-09-27T00:45:28.495Z',
    checkedAt: '2026-09-27T00:45:28.495Z',
    sha256: '4daca15c6264450defcb28dde2d342cd9dfdaf7beaa7e16dea30b50c1cd4116c',
  },
  near: {
    url: 'https://cloud-api.near.ai/v1/models',
    fetchedAt: '2026-09-27T00:45:28.171Z',
    checkedAt: '2026-09-27T00:45:28.171Z',
    sha256: 'fda7f59257f065c39ffc24fbfec55b49ef03219507bbda89ae199ab28eee0077',
  },
  chutes: {
    url: 'https://llm.chutes.ai/v1/models',
    fetchedAt: '2026-09-27T00:45:28.263Z',
    checkedAt: '2026-09-27T00:45:28.263Z',
    sha256: '21eb637461ac7148c58b992caa85694130f152ce30df34c20ccf42dc902df053',
  },
  phala: {
    url: 'https://service.redpill.ai/api/models',
    fetchedAt: '2026-09-27T00:45:28.501Z',
    checkedAt: '2026-09-27T00:45:28.501Z',
    sha256: '27231dcfc73c34047e7e33d19246c478f6de30c679296d0869d75a9e01bdf908',
  },
  darkbloom: {
    url: 'https://api.darkbloom.dev/v1/models/catalog',
    fetchedAt: '2026-09-27T00:45:28.325Z',
    checkedAt: '2026-09-27T00:45:28.325Z',
    sha256: '40968aded24aed874f44915389c46fc0d24980565457f6966a5127a9ab1ce690',
  },
};
